apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: schepuri-eks-cd-org/immport-portal
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.WRITE_DOCKER_REGISTRY}}/{{.IMAGE_NAME}}:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: '{{.WRITE_DOCKER_REGISTRY}}/{{.IMAGE_NAME}}:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: immport-portal
        chartPath: charts/immport-portal
        setValueTemplates:
          image.repository: '{{.WRITE_DOCKER_REGISTRY}}/{{.IMAGE_NAME}}'
          image.tag: '{{.DIGEST_HEX}}'
